

--1-CREATE LOGIN -----
CREATE LOGIN HOSSAM_SERVER WITH PASSWORD='123456' 

--2-CREATE USER -------
CREATE USER HALA FOR LOGIN HOSSAM_SERVER
CREATE USER AHMED FOR LOGIN HOSSAM_SERVER;

--3-ADD PERMETION TO HALA ---
GRANT SELECT ON SALES.Orders TO  HALA 
grant SELECT ON SALES.Customers TO  HALA ;
grant SELECT ON HR.Employees TO  HALA ;


---4-remove permitions------
REVOKE SELECT ON SALES.Orders TO  HALA ;
