
---SECURITY ON DATABASE 


--1-CREATE LOGIN -----
CREATE LOGIN HOSSAM_SERVER WITH PASSWORD='123456' 
CREATE LOGIN AHMED_SERVER WITH PASSWORD = '123456'

--2-CREATE USER -------
CREATE USER HALA FOR LOGIN HOSSAM_SERVER
CREATE USER AHMED FOR LOGIN AHMED_SERVER;


--3-ADD PERMETION TO HALA ---
---HR ---
GRANT SELECT ON HR.Employees TO HALA
GRANT SELECT ON HR.Departments TO HALA
---SALES----
GRANT SELECT ON SALES.Customers TO HALA
GRANT SELECT ON  SALES.Orders TO HALA
---FINANCE-----
GRANT SELECT ON FINANCE.Expenses  TO HALA
GRANT SELECT ON  FINANCE.Expenses TO HALA

---HR ---
GRANT INSERT ON HR.Employees TO AHMED
GRANT INSERT ON HR.Departments TO AHMED
---SALES----
GRANT INSERT ON SALES.Customers TO AHMED
GRANT INSERT ON  SALES.Orders TO AHMED
---FINANCE-----
GRANT INSERT ON FINANCE.Expenses  TO AHMED
GRANT INSERT ON  FINANCE.Expenses TO AHMED


-----------------------------------------------------------
---4-remove permitions------
--FROM READER ---
REVOKE SELECT ON HR.Employees TO HALA
REVOKE SELECT ON HR.Departments TO HALA
---SALES----
REVOKE SELECT ON SALES.Customers TO HALA
REVOKE SELECT ON  SALES.Orders TO HALA
---FINANCE-----
REVOKE SELECT ON FINANCE.Expenses  TO HALA
REVOKE SELECT ON  FINANCE.Expenses TO HALA

---FROM WRITER---
---HR ---
REVOKE INSERT ON HR.Employees TO AHMED
REVOKE INSERT ON HR.Departments TO AHMED
---SALES----
REVOKE INSERT ON SALES.Customers TO AHMED
REVOKE INSERT ON  SALES.Orders TO AHMED
---FINANCE-----
REVOKE INSERT ON FINANCE.Expenses  TO AHMED
REVOKE INSERT ON  FINANCE.Expenses TO AHMED
